version: 2

project_name: brht

before:
    hooks:
        - go mod tidy

builds:
    - id: brht
      main: ./cmd/brht
      binary: brht
      env:
          - CGO_ENABLED=0
      goos:
          - linux
          - darwin
          - windows
      goarch:
          - amd64
          - arm64
      ignore:
          - goos: windows
            goarch: arm64
      ldflags:
          - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}}

archives:
    - id: brht-archive
      ids:
          - brht
      name_template: >-
          {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
      formats: [tar.gz]
      format_overrides:
          - goos: windows
            formats: [zip]
      files:
          - README.md
          - LICENSE

checksum:
    name_template: "checksums.txt"

snapshot:
    version_template: "{{ incpatch .Version }}-next"

changelog:
    sort: asc
    filters:
        exclude:
            - "^docs:"
            - "^test:"
            - "^ci:"

release:
    github:
        owner: s4nj1th
        name: brht
    draft: false
    prerelease: auto
